apiVersion: v1
kind: Pod
metadata:
  name: kube-netutils
  labels:
    app: kube-netutils
spec:
  securityContext:
    runAsUser: 1000              
    runAsNonRoot: true
    fsGroup: 1000                
  containers:
    - name: kube-netutils
      image: kube-netutils:latest
      command: ["sleep", "infinity"]
      securityContext:
        allowPrivilegeEscalation: false
        privileged: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        capabilities:
          drop:
            - ALL
      volumeMounts:
        - name: tmp
          mountPath: /tmp
  volumes:
    - name: tmp
      emptyDir: {}
