name: Build, Scan, and Push kube-netutils Image

on:
  push:
    branches:
      - main

jobs:
  build-and-scan:
    name: Build, Scan, and Push Docker Image
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: cloudopsknight/kube-netutils
      IMAGE_TAG: ${{ github.sha }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t docker.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

      - name: Run Trivy (human-readable output)
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: docker.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: table
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 0  # Print results, but don’t fail yet

      - name: Run Trivy (SARIF for GitHub Security tab + hard fail)
        id: trivy-scan
        uses: aquasecurity/trivy-action@7b7aa264d83dc58691451798b4d117d53d21edfe
        with:
          image-ref: docker.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: CRITICAL,HIGH
          ignore-unfixed: true
          exit-code: 1  # Fail step if high/critical found

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

      - name: Push Docker Image to Docker Hub
        if: success()  # Only runs if scan above didn't fail
        run: |
          docker push docker.io/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
